### PR TITLE
re-structure the project with standard template

### PR DESCRIPTION
**Pull request by wj-Mcat**
## Description

try to finish the plan: https://github.com/tata1661/FSL-Mate/issues/24

I don't modify the content of source code but the project structure which is added into some more useful tools to make it more extensive, eg:

* Makefile: workflow scripts
* requirements-dev.txt: dependency packages only used in developemtn
* pyproject.toml: store the project metadata which can be used in many opensource toos, eg: pytest, mypy, pylint.

Another work in this pr: move the `paddlefsl` to the root dir to make it more clear about the source code. 

To get the details, you can read the project tree structure in files of pr.

### CODE REVIEW

**Comment by wj-Mcat** [comment]
You can read the project structure from here:

image

**Comment by wj-Mcat** [comment]
`VERSION` file will mark a `dev` tag to the published package.

**Comment by tata1661** [comment]
@wj-Mcat Thanks for your contribution! 
This repo serves as a tool for users to quickly find resources of FSL, which is not limited to Paddle codes. 
Thus, we would rather keep PaddleFSL as a subdirectory in FSL-Mate. 

Except that, the other changes are nice. However, this branch has conflict with the current FSL-Mate. Please double check with your PR.

**Comment by tata1661** [comment]
> I understand this repo acts as a tool for developers who use paddle to creat model. 

@wj-Mcat  This is not the aim of this repo. 

As said before, ``this repo serves as a tool for users to quickly find resources of FSL, which is not limited to Paddle codes". 
We care about both people from academics and industry, wishing to contribute to the advances of FSL. This is not limited to offering codes. 
We include paper list, and paddle codes so far. We may also provide codes in other frameworks  or some tutorials on FSL in the future.

**Comment by wj-Mcat** [comment]
OK, I will convert it back. 😆  please wait for my new commits.

**Comment by wj-Mcat** [comment]
I have converted it to `PaddleFSL` subdirectory structure. please review it when you are free. @tata1661

**Comment by wj-Mcat** [comment]
不好意思，我这周在准备学校毕业答辩的相关事情，等周五过后我会继续推进这个PR。

**Comment by wj-Mcat** [comment]
I have set the CICD workflow script for project, which contains:

- [x] make unittest with pytest, all of you should do is: `make test`
- [x] make code linting with mypy, pylint, flake8, all of you should do is:  `make test`
- [x] use `requirements.txt` to store the production packages.  use `requirements-dev.txt` to store the development packages.
- [x] use `pyproject.toml` file to store the configurations of different tools, eg: pytest, mypy.
- [ ] automaticlly deploy the package to the pypi server, but you should set secret token, named as `PYPI_TOKEN`, in project setting. feature should be tested.

**Comment by tata1661** [comment]
@wj-Mcat Thanks! I am also busy working on several DDLs. I will check your commits later this week.

**Comment by wj-Mcat** [comment]
Closed according to https://github.com/tata1661/FSL-Mate/issues/24, I'll work on the dev branch.

**Pull request closed without merging**
